package jdbcgui;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class AddManager extends javax.swing.JFrame {

    /**
     * Creates new form AddManager
     */
   myDBCon dbCon;
   ResultSet rs;

    public AddManager() {
        initComponents();
        // center form in screen 
        this.setLocationRelativeTo(null);
        // set all error labels to invisible
        lblMgrnameError.setVisible(false);
        lblMgrLnameError.setVisible(false);
        lblmgridError.setVisible(false);
        lblSalaryError.setVisible(false);
       // lblCommError.setVisible(false);

        //populate mgr and deptno combo boxes 
        //populate validmgr numbers
       try {
          
            dbCon = new myDBCon();
            //rs = dbCon.executeStatement("SELECT id, first_name, last_name, salary,team_id  FROM managers ORDER BY id ASC ");

            // populate mgr combo box
          /*  while (rs.next()) {
                cmbMgr.addItem(rs.getString("empno"));
            }*/

            // get and populate valid department numbers 
            rs = dbCon.executeStatement("Select team_id from teams where mgr_id is null ORDER BY team_id ASC");        
           

            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMgrname = new javax.swing.JTextField();
        txtMgrLname = new javax.swing.JTextField();
        txtmgrid = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnAddNewManager = new javax.swing.JButton();
        lblMgrnameError = new javax.swing.JLabel();
        lblmgridError = new javax.swing.JLabel();
        lblMgrLnameError = new javax.swing.JLabel();
        lblSalaryError = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Manager");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Manager");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("SALARY:");

        txtMgrname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtMgrLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtmgrid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmgrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmgridActionPerformed(evt);
            }
        });

        txtSalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewManager.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewManager.setText("Add New");
        btnAddNewManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewManagerActionPerformed(evt);
            }
        });

        lblMgrnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblMgrnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblMgrnameError.setText("error label");

        lblmgridError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblmgridError.setForeground(new java.awt.Color(255, 0, 0));
        lblmgridError.setText("error label");

        lblMgrLnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblMgrLnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblMgrLnameError.setText("error label");

        lblSalaryError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblSalaryError.setForeground(new java.awt.Color(255, 0, 0));
        lblSalaryError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMgrLname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMgrname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmgrid, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddNewManager, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMgrnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMgrLnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSalaryError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmgridError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmgrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMgrname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMgrLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(lblMgrLnameError)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblSalaryError))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblmgridError)
                            .addGap(18, 18, 18)
                            .addComponent(lblMgrnameError))))
                .addGap(33, 33, 33)
                .addComponent(btnAddNewManager)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmgridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmgridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmgridActionPerformed

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() {
        lblMgrnameError.setText("");
        lblMgrnameError.setVisible(false);
        lblMgrLnameError.setText("");
        lblMgrLnameError.setVisible(false);
        lblmgridError.setText("");
        lblmgridError.setVisible(false);
        lblSalaryError.setText("");
        lblSalaryError.setVisible(false);
        

    }

    boolean isValidData() {

        clearErrorLabels();
        boolean result = true;
        if (txtmgrid.getText().trim().isEmpty() || !isInteger(txtmgrid.getText().trim())) {
            if (txtmgrid.getText().trim().isEmpty()) {
                lblmgridError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtmgrid.getText().trim())) {
                lblmgridError.setText("Invalid. Must be integer.");
            }

            lblmgridError.setVisible(true);
            result = false;
        }

        if (txtMgrLname.getText().trim().isEmpty() || (txtMgrLname.getText().trim().length() > 24)) {
            if (txtMgrLname.getText().trim().isEmpty()) {
                lblMgrLnameError.setText("Invalid. Cannot be empty.");
            } else if ((txtMgrLname.getText().trim().length() > 24)) {
                lblMgrLnameError.setText("Invalid. Must be < 26 chars.");
            }

            lblMgrLnameError.setVisible(true);
            result = false;
        }

        if (txtMgrname.getText().trim().isEmpty() || (txtMgrname.getText().trim().length() > 24)) {
            if (txtMgrname.getText().trim().isEmpty()) {
                lblMgrnameError.setText("Invalid. Cannot be empty.");
            } else if (txtMgrname.getText().trim().length() > 24) {
                lblMgrnameError.setText("Invalid. Must be < 25 chars.");
            }
            lblMgrnameError.setVisible(true);
            result = false;
        }

      /*  if (ftxtHiredate.getText().trim().isEmpty()) {
            lblHiredateError.setText("Invalid. Cannot be empty.");
            lblHiredateError.setVisible(true);
            result = false;
        }*/

        if (txtSalary.getText().trim().isEmpty() || !(isInteger(txtSalary.getText().trim()) || isDouble(txtSalary.getText().trim()))) {
            if (txtSalary.getText().trim().isEmpty()) {
                lblSalaryError.setText("Invalid. Cannot be empty.");
            } else if (!(isInteger(txtSalary.getText().trim()) || isDouble(txtSalary.getText().trim()))) {
                lblSalaryError.setText("Invalid. Must be number.");
            }

            lblSalaryError.setVisible(true);
            result = false;
        }

     /*   if (txtComm.getText().trim().isEmpty() || !isInteger(txtComm.getText().trim())) {
            if (txtComm.getText().trim().isEmpty()) {
                lblCommError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtComm.getText().trim())) {
                lblCommError.setText("Invalid. Must be integer");
            }

            lblCommError.setVisible(true);
            result = false;
        }*/

        return result;
    }

    void clearInputBoxes() {
        txtMgrname.setText("");
        txtMgrLname.setText("");
        txtmgrid.setText("");
        txtSalary.setText("");
   
    }

   /* private boolean isDuplicate(int empno) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "Select empno FROM emp WHERE empno = "+empno;
        rs = dbCon.executeStatement(stmtSQL);
        //isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();
        
        return isduplicate;
    }*/
    private void btnAddNewManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewManagerActionPerformed
        // TODO add your handling code here:

        try {
            // make the result set scrolable forward/backward updatable
 

            if (isValidData()) {
                String prepSQL = "INSERT INTO MANAGERS (id, first_name, last_name, salary) VALUES ( "
                + txtmgrid.getText().trim() + ","
                + "'"+txtMgrname.getText()+ "',"
                + "'"+ txtMgrLname.getText() + "',"
                + txtSalary.getText()+ ")";
                
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Manager added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    clearInputBoxes();
                } else {
                    // check validation errors 
                }

                rs.close();
            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new Manager." + e.getMessage());
        }
    }//GEN-LAST:event_btnAddNewManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMgrLnameError;
    private javax.swing.JLabel lblMgrnameError;
    private javax.swing.JLabel lblSalaryError;
    private javax.swing.JLabel lblmgridError;
    private javax.swing.JTextField txtMgrLname;
    private javax.swing.JTextField txtMgrname;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtmgrid;
    // End of variables declaration//GEN-END:variables
}
