/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcgui;

/**
 *
 * @author ibrahim
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class AddTeams extends javax.swing.JFrame {

    /**
     * Creates new form AddTeams
     */
    
      myDBCon dbCon;
      ResultSet rs;
      
    public AddTeams() {
        initComponents();
       
        // center form in screen 
        this.setLocationRelativeTo(null);
        clearErrorLabels();
        // set all error labels to invisible
            dbCon = new myDBCon();
            
            getNewData();
            }
    
    private void getNewData(){
       
        try {
            
          rs = dbCon.executeStatement("select distinct id from managers, teams where id not in (select mgr_id from teams)");        
            
          cmbManagerID.removeAllItems();
          while (rs.next()) {
                cmbManagerID.addItem(rs.getString("id"));
            }
             
             rs.beforeFirst();
             rs.first();
              populateFields();
            } catch (SQLException e) {
                System.out.println(e);
            }
    }
    
    private void populateFields() {
        try {
              cmbManagerID.setSelectedItem(rs.getString("id"));
              
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblManagerID = new javax.swing.JLabel();
        lblHomeGround = new javax.swing.JLabel();
        txtTeamName = new javax.swing.JTextField();
        txtHomeGround = new javax.swing.JTextField();
        lblErrorTeamName = new javax.swing.JLabel();
        lblErrorManagerID = new javax.swing.JLabel();
        lblErrorHomeGround = new javax.swing.JLabel();
        btnAddTeam = new javax.swing.JButton();
        txtTeamID = new javax.swing.JTextField();
        lblTeamID = new javax.swing.JLabel();
        lblErrorTeamID = new javax.swing.JLabel();
        cmbManagerID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Team");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name");

        lblManagerID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblManagerID.setText("Manager ID");

        lblHomeGround.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHomeGround.setText("Home Ground");

        lblErrorTeamName.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorTeamName.setText("Error");

        lblErrorManagerID.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorManagerID.setText("Error");

        lblErrorHomeGround.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorHomeGround.setText("Error");

        btnAddTeam.setText("Add New");
        btnAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeamActionPerformed(evt);
            }
        });

        lblTeamID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTeamID.setText("Team ID");

        lblErrorTeamID.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorTeamID.setText("Error");

        cmbManagerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbManagerIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblHomeGround)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHomeGround))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName)
                                            .addComponent(lblTeamID))
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblManagerID)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTeamID, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtTeamName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorTeamName)
                            .addComponent(lblErrorManagerID)
                            .addComponent(lblErrorHomeGround)
                            .addComponent(lblErrorTeamID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnAddTeam)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeamID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeamID)
                    .addComponent(lblErrorTeamID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(lblErrorTeamName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorManagerID)
                    .addComponent(lblManagerID)
                    .addComponent(cmbManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHomeGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorHomeGround)
                    .addComponent(lblHomeGround))
                .addGap(32, 32, 32)
                .addComponent(btnAddTeam)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeamActionPerformed
        // TODO add your handling code here:
        
        
        try {
            
            if (isValidData()) {
                String prepSQL = "INSERT INTO teams (team_id, team_name, mgr_id, home_ground) VALUES ( "
                + txtTeamID.getText().trim() + " ,"
                +"'"+txtTeamName.getText().trim() + "',"
                +cmbManagerID.getSelectedItem().toString() +","
                + "'"+ txtHomeGround.getText().trim() + "')";
                
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New team added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    getNewData();
                    clearInputBoxes();
                } else {
                    // check validation errors 
                }

                rs.close();
            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }  
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new team." + e.getMessage());       
        }      
    }//GEN-LAST:event_btnAddTeamActionPerformed

    private void cmbManagerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbManagerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbManagerIDActionPerformed

    /**
     * @param args the command line arguments
     */
    
     void clearInputBoxes() {
        txtTeamName.setText("");
        txtHomeGround.setText("");
        cmbManagerID.setSelectedIndex(0);
    }
    
    
     public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
     void clearErrorLabels() {
        lblErrorTeamID.setText("");
        lblErrorTeamID.setVisible(false);
        lblErrorTeamName.setText("");
        lblErrorTeamName.setVisible(false);
        lblErrorHomeGround.setText("");
        lblErrorHomeGround.setVisible(false);
        lblErrorManagerID.setText("");
        lblErrorManagerID.setVisible(false);
        
    } 
     
    
    boolean isValidData() {

        clearErrorLabels();
        boolean result = true;
        if (txtTeamName.getText().trim().isEmpty() || txtTeamName.getText().trim().length() > 50) {
            if (txtTeamName.getText().trim().isEmpty()) {
                lblErrorTeamName.setText("Invalid. Cannot be empty.");
            } else if (txtTeamName.getText().trim().length() > 50) {
                lblErrorTeamName.setText("Invalid. Must be <=50 chars.");
            }

            lblErrorTeamName.setVisible(true);
            result = false;
        }

        if (txtHomeGround.getText().trim().isEmpty() || (txtHomeGround.getText().trim().length() > 50)) {
            if (txtHomeGround.getText().trim().isEmpty()) {
                lblHomeGround.setText("Invalid. Cannot be empty.");
            } else if (txtHomeGround.getText().trim().length() >50) {
                lblHomeGround.setText("Invalid. Must be <= 50 chars.");
            }
            lblHomeGround.setVisible(true);
            result = false;
        }
  
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeam;
    private javax.swing.JComboBox<String> cmbManagerID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErrorHomeGround;
    private javax.swing.JLabel lblErrorManagerID;
    private javax.swing.JLabel lblErrorTeamID;
    private javax.swing.JLabel lblErrorTeamName;
    private javax.swing.JLabel lblHomeGround;
    private javax.swing.JLabel lblManagerID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTeamID;
    private javax.swing.JTextField txtHomeGround;
    private javax.swing.JTextField txtTeamID;
    private javax.swing.JTextField txtTeamName;
    // End of variables declaration//GEN-END:variables
}
