/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ibrahim
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    
    myDBCon dbCon;
    ResultSet rs;
    
    
    public Display() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        try {
          
            dbCon = new myDBCon();   
            
             rs = dbCon.executeStatement("SELECT Player_Name FROM GamesPlayed");
            while (rs.next()) {
                cmbPlayerName.addItem(rs.getString("Player_Name"));
            }
             
             rs = dbCon.executeStatement("Select team_name from teams");
             while (rs.next()){
                 cmbTeamName.addItem(rs.getString("team_name"));
             }
           
              rs = dbCon.executeStatement("Select match_name from MatchResults");
             while (rs.next()){
                 cmbMatchNumber.addItem(rs.getString("match_name"));
             }
             
              rs = dbCon.executeStatement("Select Manager_name from managerinfo");
             while (rs.next()){
                 cmbManager.addItem(rs.getString("Manager_name"));
             }
            
             
            
        } catch (SQLException e) {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPlayerName = new javax.swing.JComboBox<>();
        btnTotalPlayed = new javax.swing.JButton();
        cmbTeamName = new javax.swing.JComboBox<>();
        lblTeamID = new javax.swing.JLabel();
        btnWin = new javax.swing.JButton();
        btnLoss = new javax.swing.JButton();
        btnDraw = new javax.swing.JButton();
        btnPlayerTeam = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbMatchNumber = new javax.swing.JComboBox<>();
        btnResults = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbManager = new javax.swing.JComboBox<>();
        btnManager = new javax.swing.JButton();
        btnTeamInfo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Display Info");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 9, 153, 49));

        jLabel2.setText("Player Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 68, -1, -1));

        getContentPane().add(cmbPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 65, 196, -1));

        btnTotalPlayed.setText("Total Matches Played");
        btnTotalPlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPlayedActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotalPlayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 126, 196, -1));

        getContentPane().add(cmbTeamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 251, 197, -1));

        lblTeamID.setText("Team Name: ");
        getContentPane().add(lblTeamID, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 254, -1, -1));

        btnWin.setText("Wins");
        btnWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWinActionPerformed(evt);
            }
        });
        getContentPane().add(btnWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 316, -1, -1));

        btnLoss.setText("Losses");
        btnLoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLossActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 316, -1, -1));

        btnDraw.setText("Draws");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });
        getContentPane().add(btnDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 316, -1, -1));

        btnPlayerTeam.setText("Player Information");
        btnPlayerTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerTeamActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayerTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 94, 196, -1));

        jLabel3.setText("Match Results");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 357, -1, -1));

        getContentPane().add(cmbMatchNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 354, 195, -1));

        btnResults.setText("Results");
        btnResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultsActionPerformed(evt);
            }
        });
        getContentPane().add(btnResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 383, 195, -1));

        jLabel4.setText("Manager Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 168, -1, -1));

        getContentPane().add(cmbManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 165, 174, -1));

        btnManager.setText("Manager Information");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 200, 174, -1));

        btnTeamInfo.setText("Team Information");
        btnTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeamInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 284, 197, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalPlayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPlayedActionPerformed
        // TODO add your handling code here:
        
      
        try{
        String strSQL = "select Player_Name, matches_played" +
                " from gamesplayed "+  
                "where Player_Name = '" + cmbPlayerName.getSelectedItem().toString() + "'";
        
        
        int result = dbCon.executePrepared(strSQL);
       
        
        rs = dbCon.executeStatement(strSQL);
        
        rs.next();
        
        String matchesplayed = rs.getString("matches_played");
        String pname = rs.getString("Player_Name");
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel( pname + " played " + matchesplayed + " matches." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Player", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
         
         
         
        } catch (SQLException e){
            
             JOptionPane.showMessageDialog(null, "Error obtaining info." + e.getMessage());
        }
        
    }//GEN-LAST:event_btnTotalPlayedActionPerformed

    private void btnLossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLossActionPerformed
        // TODO add your handling code here:
        
        try{
        String strSQL = "select team_name, losses " +
        "from TeamLosses " +
        "where team_name ='" + cmbTeamName.getSelectedItem().toString() +"'";
       
        
        int result = dbCon.executePrepared(strSQL);
       
        
        rs = dbCon.executeStatement(strSQL);
        
        rs.next();
        
        String matchesloss = rs.getString("losses");
        String team_name = rs.getString("team_name");
        
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel(team_name +" lost " + matchesloss + " matches." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
        }catch (SQLException e){
                          javax.swing.JLabel label = new javax.swing.JLabel("Lost 0 Matches");
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnLossActionPerformed

    private void btnWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWinActionPerformed
        // TODO add your handling code here:
        try{
        String strSQL = "select team_name, wins " +
        "from TeamWins " +
        "where team_name ='" + cmbTeamName.getSelectedItem().toString() +"'";
        
        
        int result = dbCon.executePrepared(strSQL);
     rs = dbCon.executeStatement(strSQL);
        
        rs.next();
        
        String matcheswon = rs.getString("wins");
        String team_name = rs.getString("team_name");
        
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel(team_name + " won " + matcheswon + " matches." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
        
        } catch (SQLException e){
              javax.swing.JLabel label = new javax.swing.JLabel("Won 0 Matches");
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnWinActionPerformed

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        // TODO add your handling code here:
        try{
        String strSQL = "select team_name, draws " +
        "from TeamDraws " +
        "where team_name ='" + cmbTeamName.getSelectedItem().toString() +"'";        
        
        int result = dbCon.executePrepared(strSQL);
       
        
        rs = dbCon.executeStatement(strSQL);
        
        rs.next();
        
        String matchesdraw = rs.getString("draws");
        String team_name = rs.getString("team_name");
        
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel(team_name + " has drawn " + matchesdraw + " matches." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
        } catch (SQLException e){
                          javax.swing.JLabel label = new javax.swing.JLabel("Drawn 0 Matches");
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDrawActionPerformed

    private void btnPlayerTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerTeamActionPerformed
        // TODO add your handling code here:
                try{
        String strSQL = "select Player_Name, team_name, position,salary" +
                " from gamesplayed "+  
                "where Player_Name = '" + cmbPlayerName.getSelectedItem().toString() + "'";
        
        
        int result = dbCon.executePrepared(strSQL);

        rs = dbCon.executeStatement(strSQL);
        rs.next();
        
        String teamname = rs.getString("team_name");
        String pname = rs.getString("Player_Name");
        String psalary = rs.getString("Salary");
        String position = rs.getString("Position");
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel(pname + " plays for " + teamname + " at position "+position+ "."+" Player's Salary = $"+psalary+"." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
        
        } catch (SQLException e){
            
             JOptionPane.showMessageDialog(null, "Error obtaining info." + e.getMessage());
        }
        
    }//GEN-LAST:event_btnPlayerTeamActionPerformed

    private void btnResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultsActionPerformed
        // TODO add your handling code here:
         try{
        String strSQL = "select home, home_goals, visitor, visitor_goals, result" +
                " from MatchResults "+  
                "where match_name = '" + cmbMatchNumber.getSelectedItem() + "'";
        
        
        int result = dbCon.executePrepared(strSQL);

        rs = dbCon.executeStatement(strSQL);
        rs.next();
        
        String home = rs.getString("home");
        String visitor = rs.getString("visitor");
        String home_goals = rs.getString("home_goals");
        String visitor_goals = rs.getString("visitor_goals");
        int matchresult = rs.getInt("result");
        
        if (result > 0){

            if (matchresult == 1){
                
                 javax.swing.JLabel label = new javax.swing.JLabel(home + " won the match against " + visitor + " with a score of " + home_goals + " - " + visitor_goals );
                 label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                 JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (matchresult == 2){
                javax.swing.JLabel label = new javax.swing.JLabel(visitor + " won the match against " + home + " with a score of " +visitor_goals  + " - " + home_goals);
                 label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                 JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                
                javax.swing.JLabel label = new javax.swing.JLabel("The match between "+ home + " and "+ visitor +" was drawn with a score of "+ home_goals + " - " + visitor_goals);
                 label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                 JOptionPane.showMessageDialog(null, label, "Result", JOptionPane.INFORMATION_MESSAGE);
            }
            
        
        } else {        
        
        }
        
        } catch (SQLException e){
            
             JOptionPane.showMessageDialog(null, "Error obtaining info." + e.getMessage());
        }
        
    }//GEN-LAST:event_btnResultsActionPerformed

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
         try{
        String strSQL = "select Manager_Name, team_name, salary" +
                " from managerinfo "+  
                "where Manager_Name = '" + cmbManager.getSelectedItem().toString() + "'";
        
        
        int result = dbCon.executePrepared(strSQL);

        rs = dbCon.executeStatement(strSQL);
        rs.next();
        
        String teamname = rs.getString("team_name");
        String mname = rs.getString("Manager_Name");
        String msalary = rs.getString("Salary");
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel(mname + " manages " + teamname + "."+ " Manager's Salary = $"+msalary+"." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Manager", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
        
        } catch (SQLException e){
            
             JOptionPane.showMessageDialog(null, "Error obtaining info." + e.getMessage());
        }
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeamInfoActionPerformed
        // TODO add your handling code here:
        
        try{
        String strSQL = "select Manager_Name, team_name, home_ground" +
                " from teaminfo "+  
                "where team_Name = '" + cmbTeamName.getSelectedItem().toString() + "'";
        
        
        int result = dbCon.executePrepared(strSQL);

        rs = dbCon.executeStatement(strSQL);
        rs.next();
        
        String teamname = rs.getString("team_name");
        String mname = rs.getString("Manager_Name");
        String homeground = rs.getString("home_ground");
        
        if (result > 0){
                          javax.swing.JLabel label = new javax.swing.JLabel(teamname+ " is managed by " + mname + ". "+teamname+ " home ground is " +homeground+"." );
                          label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                          JOptionPane.showMessageDialog(null, label, "Team", JOptionPane.INFORMATION_MESSAGE);
                            
                         }
                         else {        
                         }
        
        } catch (SQLException e){
            
             JOptionPane.showMessageDialog(null, "Error obtaining info." + e.getMessage());
        }
    }//GEN-LAST:event_btnTeamInfoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDraw;
    private javax.swing.JButton btnLoss;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnPlayerTeam;
    private javax.swing.JButton btnResults;
    private javax.swing.JButton btnTeamInfo;
    private javax.swing.JButton btnTotalPlayed;
    private javax.swing.JButton btnWin;
    private javax.swing.JComboBox<String> cmbManager;
    private javax.swing.JComboBox<String> cmbMatchNumber;
    private javax.swing.JComboBox<String> cmbPlayerName;
    private javax.swing.JComboBox<String> cmbTeamName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTeamID;
    // End of variables declaration//GEN-END:variables
}
