/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcgui;

/**
 *
 * @author wissam
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    LoginUser userr;
    public Menu(LoginUser userr) {
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.userr = userr;
        
        Display.setVisible(true);
        
        if (userr.type == 1){
           User.setVisible(false);
           Players.setVisible(false);
           Manager.setVisible(false);
           Teams.setVisible(false);
           Matches.setVisible(false);
        }
        else if(userr.type == 0){
             User.setVisible(true);
             Players.setVisible(true);
             Manager.setVisible(true);
             Teams.setVisible(true);
             Matches.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Players = new javax.swing.JMenu();
        AddPlayer = new javax.swing.JMenuItem();
        UpdateDeletePlayer = new javax.swing.JMenuItem();
        Teams = new javax.swing.JMenu();
        AddTeam = new javax.swing.JMenuItem();
        UpdateDeleteTeam = new javax.swing.JMenuItem();
        Manager = new javax.swing.JMenu();
        AddManager = new javax.swing.JMenuItem();
        UpdateDeleteManager = new javax.swing.JMenuItem();
        Matches = new javax.swing.JMenu();
        AddMatch = new javax.swing.JMenuItem();
        UpdateDeleteMatches = new javax.swing.JMenuItem();
        User = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        Display = new javax.swing.JMenu();
        DisplayStuff = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - JDBC GUI");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/b417b8e05cee70b4bbf0f82307e08a18.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/logout.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/close.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        Players.setText("Players");
        Players.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        AddPlayer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AddPlayer.setText("Add Player");
        AddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlayerActionPerformed(evt);
            }
        });
        Players.add(AddPlayer);

        UpdateDeletePlayer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        UpdateDeletePlayer.setText("Update/Delete Player");
        UpdateDeletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeletePlayerActionPerformed(evt);
            }
        });
        Players.add(UpdateDeletePlayer);

        jMenuBar1.add(Players);

        Teams.setText("Teams");
        Teams.setToolTipText("");
        Teams.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Teams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamsActionPerformed(evt);
            }
        });

        AddTeam.setText("Add Team");
        AddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeamActionPerformed(evt);
            }
        });
        Teams.add(AddTeam);

        UpdateDeleteTeam.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        UpdateDeleteTeam.setText("Update/Delete Team");
        UpdateDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteTeamActionPerformed(evt);
            }
        });
        Teams.add(UpdateDeleteTeam);

        jMenuBar1.add(Teams);

        Manager.setText("Managers");
        Manager.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N

        AddManager.setText("Add Manager");
        AddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddManagerActionPerformed(evt);
            }
        });
        Manager.add(AddManager);

        UpdateDeleteManager.setText("Update/Delete Manager");
        UpdateDeleteManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteManagerActionPerformed(evt);
            }
        });
        Manager.add(UpdateDeleteManager);

        jMenuBar1.add(Manager);

        Matches.setText("Matches");
        Matches.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N

        AddMatch.setText("Add Match");
        AddMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMatchActionPerformed(evt);
            }
        });
        Matches.add(AddMatch);

        UpdateDeleteMatches.setText("Update/Delete Matches ");
        UpdateDeleteMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleteMatchesActionPerformed(evt);
            }
        });
        Matches.add(UpdateDeleteMatches);

        jMenuBar1.add(Matches);

        User.setText("User");
        User.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Add New User");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        User.add(jMenuItem8);

        jMenuItem9.setText("Update/Delete User");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        User.add(jMenuItem9);

        jMenuBar1.add(User);

        Display.setText("Display");
        Display.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        DisplayStuff.setText("Display");
        DisplayStuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayStuffActionPerformed(evt);
            }
        });
        Display.add(DisplayStuff);

        jMenuBar1.add(Display);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlayerActionPerformed
        // TODO add your handling code here:
        (new AddPlayer()).setVisible(true);
    }//GEN-LAST:event_AddPlayerActionPerformed

    private void UpdateDeletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeletePlayerActionPerformed
        // TODO add your handling code here:
        (new UpdateDeletePlayer()).setVisible(true);

    }//GEN-LAST:event_UpdateDeletePlayerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void UpdateDeleteTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteTeamActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteTeams()).setVisible(true);
    }//GEN-LAST:event_UpdateDeleteTeamActionPerformed

    private void TeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamsActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        (new AddUser()).setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteUser()).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
         (new AddTeams()).setVisible(true);
    }//GEN-LAST:event_UserActionPerformed

    private void AddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeamActionPerformed
        // TODO add your handling code here:
           (new AddTeams()).setVisible(true);
    }//GEN-LAST:event_AddTeamActionPerformed

    private void AddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddManagerActionPerformed
        // TODO add your handling code here:
        (new AddManager()).setVisible(true);
    }//GEN-LAST:event_AddManagerActionPerformed

    private void UpdateDeleteMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteMatchesActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteMatches()).setVisible(true);
    }//GEN-LAST:event_UpdateDeleteMatchesActionPerformed

    private void AddMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMatchActionPerformed
        // TODO add your handling code here:
        (new AddMatches()).setVisible(true);
    }//GEN-LAST:event_AddMatchActionPerformed

    private void UpdateDeleteManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleteManagerActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteManager()).setVisible(true);
    }//GEN-LAST:event_UpdateDeleteManagerActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
        (new Display()).setVisible(true);
    }//GEN-LAST:event_DisplayActionPerformed

    private void DisplayStuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayStuffActionPerformed
        // TODO add your handling code here:
         (new Display()).setVisible(true);

    }//GEN-LAST:event_DisplayStuffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddManager;
    private javax.swing.JMenuItem AddMatch;
    private javax.swing.JMenuItem AddPlayer;
    private javax.swing.JMenuItem AddTeam;
    private javax.swing.JMenu Display;
    private javax.swing.JMenuItem DisplayStuff;
    private javax.swing.JMenu Manager;
    private javax.swing.JMenu Matches;
    private javax.swing.JMenu Players;
    private javax.swing.JMenu Teams;
    private javax.swing.JMenuItem UpdateDeleteManager;
    private javax.swing.JMenuItem UpdateDeleteMatches;
    private javax.swing.JMenuItem UpdateDeletePlayer;
    private javax.swing.JMenuItem UpdateDeleteTeam;
    private javax.swing.JMenu User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
